-- CREATE TABLE CLIENT
CREATE TABLE CLIENT ( /*Patient*/
	ClientID		VARCHAR(12)		NOT NULL,
	PName			VARCHAR(50)		NOT NULL,
	DOB			 	DATE			NOT NULL,
	PhysicianID		VARCHAR(12)		NOT NULL,
CONSTRAINT CLIENT_PKEY PRIMARY KEY (ClientID)
);

CREATE TABLE OUTCLIENT ( /*Patient that do NOT need to stay overnight at ward*/
	ClientID			VARCHAR(12)		NOT NULL,
	DayBedNumber		VARCHAR(3)		NULL,
CONSTRAINT OUTCLIENT_PKEY PRIMARY KEY (ClientID),
CONSTRAINT OUTCLIENT_FKEY1 FOREIGN KEY (ClientID) REFERENCES CLIENT (ClientID)
);

CREATE TABLE INCLIENT ( /*Patient that need to stay overnight at ward*/
	ClientID		VARCHAR(12)		NOT NULL,
	WardNumber		VARCHAR(3)		NOT NULL,
	BedNumber		VARCHAR(3)		NOT NULL,
CONSTRAINT INCLIENT_PKEY PRIMARY KEY (ClientID),
CONSTRAINT INCLIENT_FKEY1 FOREIGN KEY (ClientID) REFERENCES CLIENT (ClientID)
);

-- CREATE TABLE PHYSICIAN
CREATE TABLE PHYSICIAN (
	PhysicianID		VARCHAR(12)		NOT NULL,
	DName			VARCHAR(50)		NOT NULL,
	SPECIALTY		VARCHAR(200)		NOT NULL,
	YearOfExp		DECIMAL(2)		NOT NULL,	
CONSTRAINT PHYSICIAN_PKEY PRIMARY KEY (PhysicianID)
);

-- CREATE TABLE DRUG
CREATE TABLE DRUG (
	DrugName			VARCHAR(50)		NOT NULL,
	UnitPrice			DECIMAL(7,2)		NOT NULL,
CONSTRAINT DRUG_PKEY PRIMARY KEY (DrugName),
CONSTRAINT DRUG_CHECK_UNITPRICE CHECK (UnitPrice > 0)
);

-- CREATE TABLE PRESCRIPTION
CREATE TABLE PRESCRIPTION (
	ClientID			VARCHAR(12)		NOT NULL,
	PhysicianID			VARCHAR(12)		NOT NULL,
	DrugName			VARCHAR(50)		NOT NULL,
	PrescriptionDate		DATE			NOT NULL,
	Quantity			DECIMAL(5,2)		NOT NULL,
CONSTRAINT PRESCRIPTION_PKEY PRIMARY KEY (ClientID, PhysicianID, DrugName, PrescriptionDate),
CONSTRAINT PRESCRIPTION_FKEY1 FOREIGN KEY (ClientID) REFERENCES CLIENT (ClientID),
CONSTRAINT PRESCRIPTION_FKEY2 FOREIGN KEY (PhysicianID) REFERENCES PHYSICIAN (PhysicianID),
CONSTRAINT PRESCRIPTION_FKEY3 FOREIGN KEY (DrugName) REFERENCES DRUG (DrugName),
CONSTRAINT PRESCRIPTION_CHECK_QUANTITY CHECK (QUANTITY > 0)	
);
